# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('seasons', models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winnter')], max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/flower')),
            ],
        ),
    ]
