# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_auto_20170525_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='flowers',
            field=models.ManyToManyField(blank=True, to='flowers.Flower'),
        ),
        migrations.AlterField(
            model_name='design',
            name='scenes',
            field=models.ManyToManyField(blank=True, to='flowers.Scene'),
        ),
    ]
