# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_auto_20170525_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='description',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='scene',
            old_name='description',
            new_name='detail',
        ),
    ]
