# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_auto_20170705_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='design',
            name='scenes',
            field=models.ManyToManyField(blank=True, related_name='designs', to='flowers.Scene'),
        ),
        migrations.AddField(
            model_name='userclick',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.Design'),
        ),
        migrations.AddField(
            model_name='userclick',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.Scene'),
        ),
    ]
